spring.application.name=ms-centros
server.port=8006

# Importar variables de entorno desde el archivo .env
spring.config.import=optional:configparser:properties:../../.env,optional:configparser:properties:../.env,optional:configparser:properties:.env

# ===============================
# PERFIL ACTIVO
# ===============================
spring.profiles.active=dev

# ===============================
# ENCODING
# ===============================
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true

# ===============================
# TIMEZONE
# ===============================
spring.jackson.time-zone=America/Santiago

# ===============================
# LOGGING
# ===============================
logging.level.root=INFO

# ===============================
# INTEGRACION - BDSISPRO (FHIR SERVER)
# ===============================
integration.bdsispro.url=http://localhost:8080

# SWAGGER / OPENAPI
# http://localhost:8006/swagger-ui/index.html
