name: RedNorte - CI Pipeline Backend

on:
  push:
    branches: ["main", "preprod", "qa"]
  pull_request:
    branches: ["main", "preprod", "qa"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código fuente
        uses: actions/checkout@v4

      - name: Configurar entorno JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Compilar y Ejecutar Pruebas con Maven (Inyección de Entorno)
        env:
          # Inyección de Configuraciones desde GitHub Variables
          SPRING_DATASOURCE_URL: ${{ vents.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_DRIVER_CLASS_NAME: ${{ vents.SPRING_DATASOURCE_DRIVER_CLASS_NAME }}
          FRONTEND_PORT: ${{ vents.FRONTEND_PORT }}
          POSTGRES_USER: ${{ vents.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ vents.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ vents.POSTGRES_DB }}
          DB_PORT: ${{ vents.DB_PORT }}
          SPRING_MAIL_HOST: ${{ vents.SPRING_MAIL_HOST }}
          SPRING_MAIL_PORT: ${{ vents.SPRING_MAIL_PORT }}

          # Inyección de Credenciales desde GitHub Secrets (Encriptados)
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          SPRING_MAIL_USERNAME: ${{ secrets.SPRING_MAIL_USERNAME }}
          SPRING_MAIL_PASSWORD: ${{ secrets.SPRING_MAIL_PASSWORD }}
          NOTIFICATION_SERVICE_SECRET: ${{ secrets.NOTIFICATION_SERVICE_SECRET }}

        run: |
          cd backend
          mvn clean verify
